_target_: jaxltl.rl.ppo_safe.PPOSafe

total_timesteps: 5e6
num_envs: 16
num_steps: 4096
num_minibatches: 32
update_epochs: 10
gamma: 0.998
cost_gamma: 0.998
gae_lambda: 0.95
clip_eps: 0.2
ent_coef: 0.003
vf_coef: 0.5
cost_vf_coef: 0.5
lag_coef: 0.5
lr: 3e-4
max_grad_norm: 0.5
anneal_lr: false
adam_eps: 1e-8
target_cost: -0.05
min_lag: 1e-2
max_lag: 5.0
