name: deep_ltl

wrap_env:
  _target_: jaxltl.deep_ltl.wrappers.utils.wrap_env

agent:
  _target_: jaxltl.deep_ltl.eval.agent.DeepLTLAgent.instantiate
  vmap_choose_sequences: true

preprocess_formulas:
  _target_: jaxltl.deep_ltl.eval.preprocessing.preprocess_formulas
